# mongodb
spring.data.mongodb.uri = mongodb://127.0.0.1:27017/comment_task?Mechanism=SCRAM-SHA-1
# redis
spring.data.redis.url = redis://127.0.0.1:6379

# file path dir
file.upload.dir.permission=700
file.upload.dir.path = E:\\auto-task-file\\

# interact api
interact.apiUrl=https://extapi.sysjdata.com/metrics/task/
