#############mongodb####################
auto_task.uri = mongodb://auto:WzPd&lZ3hPjo@192.168.0.4:27017/auto?authSource=admin&authMechanism=SCRAM-SHA-1
mark.uri = mongodb://qbjc:9KGy$LpTa.vE@192.168.0.4:27017/qbjc?authSource=admin&authMechanism=SCRAM-SHA-1
sq.uri = mongodb://data_repository:%26KJ1RYMyLDbF@192.168.0.4:27017/data_repository?authSource=admin&authMechanism=SCRAM-SHA-1
hot_rank.uri = mongodb://hotlist:Q!RGOO7E73vW@192.168.0.4:27017/hotlist?authSource=admin&authMechanism=SCRAM-SHA-1
#############redis####################
spring.data.redis.url = redis://192.168.0.4:6379

#############file path dir####################
file.upload.dir.permission=700
file.upload.dir.path = /data/sources/auto/

########interact api
interact.apiUrl=http://192.168.0.2:8038/metrics/task/

# Swagger UI
#springdoc.swagger-ui.enabled=false
# OpenAPI
#springdoc.api-docs.enabled=false
