#############mongodb####################
auto_task.uri = mongodb://127.0.0.1:27017/auto_task?Mechanism=SCRAM-SHA-1
mark.uri = mongodb://qbjc:9KGy$LpTa.vE@183.129.194.118:27017/qbjc?authSource=admin&authMechanism=SCRAM-SHA-1
sq.uri = mongodb://data_repository:%26KJ1RYMyLDbF@183.129.194.118:27017/data_repository?authSource=admin&authMechanism=SCRAM-SHA-1
hot_rank.uri = mongodb://hotlist:Q!RGOO7E73vW@183.129.194.118:27017/hotlist?authSource=admin&authMechanism=SCRAM-SHA-1
#############redis####################
spring.data.redis.url = redis://127.0.0.1:6379

#############file path dir####################
file.upload.dir.permission=700
file.upload.dir.path = E:\\auto-task-file\\

########interact api
interact.apiUrl=https://extapi.sysjdata.com/metrics/task/
