# Mongodb
spring.data.mongodb.uri.uri = mongodb://auto:WzPd&lZ3hPjo@192.168.0.4:27017/comment_task?authSource=admin&authMechanism=SCRAM-SHA-1

# Redis
spring.data.redis.url = redis://192.168.0.4:6379

# file path dir
file.upload.dir.permission=700
file.upload.dir.path = /data/sources/auto/

# interact api
interact.apiUrl = http://192.168.0.2:8038/metrics/task/

# Swagger UI
#springdoc.swagger-ui.enabled=false
# OpenAPI
#springdoc.api-docs.enabled=false
